version: '3.8'

services:
  react-app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/news-aggregator  
    environment:
      - CHOKIDAR_USEPOLLING=true
